[package]
name = "cargo-mtukai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
cargo_metadata = "0.23.1"
walkdir = "2"
toml_edit = "0.25.11"
clap = { version = "4", features = ["derive"] }
shell-words = "1.1.1"
ra_ap_ide = "0.0.340"
ra_ap_project_model = "0.0.340"
ra_ap_load-cargo = "0.0.340"
ra_ap_vfs = "0.0.340"
ra_ap_base_db = "0.0.340"
ra_ap_syntax = "0.0.340"
ra_ap_hir = "0.0.340"

[profile.dev]
opt-level = 1