// The following code is originally based on code from the esp-rs/esp-hal project,
// licensed under the Apache License, Version 2.0 (the "License").

//! This crate provides procedural macros for the `esp-rs-copro` crate.
//! # Features
//! ## For LP coprocessor's project: with `is-lp-core` feature
//! - [`esp_rs_copro_statics`]: Defines the necessary static variables and functions to use the heap allocator from the main processor. You call this macro once.
//! ## For main processor's project: with `has-lp-core` feature
//! - [`define_lp_allocator`]: Defines the necessary static variables and functions to use the heap allocator on the LP coprocessor from the `esp-rs-copro` crate. You call this macro once. Moreover, it must be visible from [`load_lp_code2`].
//! - [`load_lp_code2`]: Load code to be run on the LP/ULP core. This macro is similar to `esp-hal`'s, however it transfers the given value to the LP memory, and the main processor sleeps.
//! ## For shared project
//! - `MovableObject` derive macro. This macro can be used to automatically implement the `MovableObject` trait for a struct or enum, which defines how to move the value to and from the LP memory.

use proc_macro::TokenStream;
use quote::quote;

fn get_crate_name(name : &str) -> proc_macro2::TokenStream {
    use proc_macro_crate::crate_name;
    use proc_macro_crate::FoundCrate;
    use proc_macro2::{Ident, Span};
    let found_crate = crate_name(name).expect(&format!("{} is present in `Cargo.toml`", name));
    match found_crate {
        FoundCrate::Itself => quote!(esp_lp_hal),
        FoundCrate::Name(name) => {
            let ident = Ident::new(&name, Span::call_site());
            quote!( #ident )
        }
    }
}

/// EntryMacroArgs := HeapSize | HeapSize "," remaining | remaining
/// remaining := item | item "," remaining
/// item :=  [(key_str "=" String)|(key_int "=" Integer)] 
/// key_int := "define_alloc_error" | "lp_start" | "lp_length" | "heap_size"
/// key_str := "path" | "arch"
struct EntryMacroArgs {
    heap_size: u32,
    define_alloc_error: bool,
    #[cfg(feature = "has-lp-core")]
    path : String,
    #[cfg(feature = "has-lp-core")]
    lp_start : Option<u32>,
    #[cfg(feature = "has-lp-core")]
    lp_length : Option<u32>
}

impl EntryMacroArgs {
    #[cfg(feature = "has-lp-core")]
    fn new(heap_size : u32, define_alloc_error : bool, path : String,
        lp_start : Option<u32>, lp_length : Option<u32>) -> Self {
        Self { heap_size, define_alloc_error, path, lp_start, lp_length }
    }
    #[cfg(not(feature = "has-lp-core"))]
    fn new(heap_size : u32, define_alloc_error : bool, _ : String,
        _ : Option<u32>, _ : Option<u32>) -> Self {
        Self { heap_size, define_alloc_error }
    }

    #[cfg(feature = "has-lp-core")]
    fn infer_lp_path(archname :&String) -> syn::Result<String> {
        use syn::Error;
        use proc_macro::Span;
        use std::path::Path;

        let manifest_dir = if let Ok(mdir) = std::env::var("CARGO_MANIFEST_DIR"){
            mdir
        } else {
            return Err(Error::new(Span::call_site().into(), "Failed to get CARGO_MANIFEST_DIR environment variable."));
        };

        let manifest_path = Path::new(&manifest_dir).join("Cargo.toml");
        let cargo_toml = if let Ok(content) = std::fs::read_to_string(manifest_path) {
            if let Ok(toml) = content.parse::<toml_edit::DocumentMut>() {
                toml
            } else {
                return Err(Error::new(Span::call_site().into(), "Failed to parse Cargo.toml."));
            }
        } else {
            return Err(Error::new(Span::call_site().into(), "Cargo.toml cannot be opened."));
        };

        if let Some(metadata) = cargo_toml.get("metadata.mtukai").and_then(|md| md.as_table()) {
            if let Some(lp_path_value) = metadata.get("lp_path").and_then(|lp_path| lp_path.as_str()) {
                if let Some(lp_bin_path) = Path::new(&lp_path_value).join("target").join(archname).join("release").join("main").to_str() {
                    Ok(lp_bin_path.to_owned())
                } else {
                    Err(Error::new(Span::call_site().into(), "The string value of metadata.mtukai.lp_path in Cargo.toml is invalid."))
                }
            } else {
                Err(Error::new(Span::call_site().into(), "The string value of metadata.mtukai.lp_path not found in Cargo.toml. Please make sure to include the lp_path field in the mtukai metadata section of your Cargo.toml, pointing to the LP binary generated by the build script."))
            }
        } else {
            Err(Error::new(Span::call_site().into(), "metadata.mtukai section not found in Cargo.toml. Please make sure to include the mtukai metadata section in your Cargo.toml."))
        }
    }
}

impl syn::parse::Parse for EntryMacroArgs {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        use syn::{LitBool, LitInt, LitStr, Token};
        #[cfg(feature="has-lp-core")]
        use {
            syn::Error,
            proc_macro::Span
        };

        let mut heap_size: Option<u32> = None;
        let mut define_alloc_error: Option<bool> = None;
        let mut path: Option<String> = None;
        let mut lp_start: Option<u32> = None;
        let mut lp_length: Option<u32> = None;
        let mut arch : Option<String> = None;

        fn update_val<V, T : syn::parse::Parse>(input: &syn::parse::ParseStream, val: &mut Option<V>, key: &str, parser: fn(T) -> syn::Result<V>) -> syn::Result<()> {
            let lit : T = input.parse()?;
            if val.is_some() {
                eprintln!("warning: duplicate `{}` in #[entry] arguments; using the last value", key);
            }
            *val = Some(parser(lit)?);
            Ok(())
        }
        
        if !input.is_empty() && input.peek(LitInt) {
            let lit: LitInt = input.parse()?;
            heap_size = Some(lit.base10_parse()?);
        }
        while !input.is_empty() {
            input.parse::<Token![,]>()?;
            if input.is_empty() {
                break;
            }

            let key: syn::Ident = input.parse()?;
            input.parse::<Token![=]>()?;

            match key.to_string().as_str() {
                "heap_size" => update_val(&input, &mut heap_size, "heap_size", |lit: LitInt| lit.base10_parse())?,
                "define_alloc_error" => update_val(&input, &mut define_alloc_error, "define_alloc_error", |lit: LitBool| Ok(lit.value))?,
                "path" => update_val(&input, &mut path, "path", |lit: LitStr| Ok(lit.value()))?,
                "lp_start" => update_val(&input, &mut lp_start, "lp_start", |lit: LitInt| lit.base10_parse())?,
                "lp_length" => update_val(&input, &mut lp_length, "lp_length", |lit: LitInt| lit.base10_parse())?,
                "arch" => update_val(&input, &mut arch, "arch", |lit: LitStr| Ok(lit.value()))?,
                _ => {
                    return Err(syn::Error::new(
                        key.span(),
                        "unknown argument; expected heap_size, define_alloc_error, path, lp_start, lp_length, or arch",
                    ));
                }
            }
        }

        #[cfg(not(feature = "has-lp-core"))]
        fn estimate_path(_: Option<String>, _: Option<String>) -> syn::Result<String> {
            Ok(String::new())
        }
        #[cfg(feature = "has-lp-core")]
        fn estimate_path(path: Option<String>, arch: Option<String>) -> syn::Result<String> {
            path.map_or_else(|| {
                let archname = arch.map_or_else(|| {
                    if cfg!(feature = "esp32c6") {
                        Ok("riscv32imac-unknown-none-elf".to_owned())
                    } else if cfg!(feature = "esp32s3") || cfg!(feature = "esp32s2") {
                        Ok("riscv32imc-unknown-none-elf".to_owned())
                    } else {
                        Err(Error::new(Span::call_site().into(), "Failed to determine target architecture by features flag. Please specify the architecture as a string literal argument, e.g., load_lp_code3!(\"riscv32-imac-unknown-none-elf\")."))
                    }
                }, Ok)?;
                EntryMacroArgs::infer_lp_path(&archname)
            }, Ok)
        }
        Ok(Self::new(heap_size.unwrap_or(0), define_alloc_error.unwrap_or(true),
            estimate_path(path, arch)?, lp_start, lp_length))
    }
}

/// Returns if the given function signature is not suitable for the entry macro.
fn check_entry_fn_signature(item : &syn::ItemFn) -> Option<syn::Error> {
    use proc_macro2::Span as Span2;
    use syn::{FnArg, Type};
    fn gen_err(msg: &str) -> Option<syn::Error> {
        Some(syn::Error::new(Span2::call_site(), msg))
    }
    // Check asyncness.
    if item.sig.asyncness.is_some() {
        return gen_err("async functions are not supported by #[entry]");
    }
    // Check arguments count.
    if item.sig.inputs.len() == 0 {
        return gen_err("Functions marked with #[entry] must have at least one argument: `&mut LpContext`. If you want to transfer any object, please add more arguments with the form `&mut T`.");
    }
    // Check the first argument is `&mut LpContext`.
    if let FnArg::Typed(pt) = &item.sig.inputs[0] // The first argument is not receiver.
    && let Type::Reference(r) = pt.ty.as_ref() // The first argument is a reference.
    && r.mutability.is_some() // and mutable.
    //check the name of ty is `LpContext`.
    && let Type::Path(p) =  r.elem.as_ref()
    && let Some(segment) =  p.path.segments.last()
    && segment.ident == "LpContext" {}
    else { return gen_err("First argument must be of type `&mut LpContext`"); }

    for arg in item.sig.inputs.iter().skip(1) {
        // Check the argument is `&mut T`.
        if let FnArg::Typed(_) = arg { } // The argument is not receiver.
        else { return gen_err("Currently, the arguments must be of type `&mut T`"); }
    }
    None
}

struct FlatField {
    name: syn::Ident,
    ty: syn::Type,
}

fn collect_flat_fields(inputs: &syn::punctuated::Punctuated<syn::FnArg, syn::token::Comma>) -> syn::Result<Vec<FlatField>> {
    use syn::{spanned::Spanned, Pat, Type, FnArg, PatType};
    fn collect_flat_fields(
        pat: &syn::Pat,
        ty: &syn::Type,
        fields: &mut Vec<FlatField>,
    ) -> syn::Result<()> {
        fn gen_wildcard_error (pat: &syn::Pat) -> syn::Result<()> {
            Err(syn::Error::new_spanned( pat, "wildcard is unsupported." ))
        }
        match (pat, ty) {
            (Pat::Ident(pat_ident), ty) => {
                if pat_ident.ident == "_" {
                    return gen_wildcard_error(pat);
                }
                fields.push(FlatField {
                    name: pat_ident.ident.clone(),
                    ty: ty.clone(),
                });
                Ok(())
            }
            (Pat::Paren(pat_paren), ty) => collect_flat_fields(pat_paren.pat.as_ref(), ty, fields),
            (Pat::Reference(pat_ref), Type::Reference(inner_ref)) => {
                collect_flat_fields(pat_ref.pat.as_ref(), inner_ref.elem.as_ref(), fields)
            }
            (Pat::Reference(pat_ref), ty) => collect_flat_fields(pat_ref.pat.as_ref(), ty, fields),
            (Pat::Tuple(pat_tuple), Type::Reference(inner_ref)) => {
                match inner_ref.elem.as_ref() {
                    Type::Tuple(inner_tuple) => {
                        if pat_tuple.elems.len() != inner_tuple.elems.len() {
                            return Err(syn::Error::new_spanned(
                                pat,
                                "tuple pattern and tuple type have different lengths",
                            ));
                        }
                        for (sub_pat, sub_ty) in pat_tuple.elems.iter().zip(inner_tuple.elems.iter()) {
                            collect_flat_fields(sub_pat, sub_ty, fields)?;
                        }
                        Ok(())
                    }
                    _ => Err(syn::Error::new_spanned(
                        pat,
                        "tuple pattern requires a tuple type",
                    )),
                }
            }
            (Pat::Tuple(pat_tuple), Type::Tuple(tuple_ty)) => {
                if pat_tuple.elems.len() != tuple_ty.elems.len() {
                    return Err(syn::Error::new_spanned(
                        pat,
                        "tuple pattern and tuple type have different lengths",
                    ));
                }
                for (sub_pat, sub_ty) in pat_tuple.elems.iter().zip(tuple_ty.elems.iter()) {
                    collect_flat_fields(sub_pat, sub_ty, fields)?;
                }
                Ok(())
            }
            // (Pat::Slice(pat_slice), Type::Array(array_ty)) => {
            //     for sub_pat in pat_slice.elems.iter() {
            //         collect_flat_fields(sub_pat, array_ty.elem.as_ref(), fields)?;
            //     }
            //     Ok(())
            // }
            (Pat::Wild(_), _) | (Pat::Rest(_), _) => gen_wildcard_error(pat),
            (Pat::Or(pat_or), _) => Err(syn::Error::new(
                pat_or.span(),
                "or-patterns are not supported because they do not denote a single value",
            )),
            _ => Err(syn::Error::new_spanned(
                pat,
                "currently supported argument patterns are identifiers, tuples, references, and parentheses", // , and slices over tuple/array types",
            )),
        }
    }
    let mut flat_fields = Vec::new();
    for arg in inputs.iter().skip(1) { // Skip the first argument: `&mut LpContext`.
        match arg {
            FnArg::Typed(PatType { pat, ty, .. }) => {
                collect_flat_fields(
                    pat.as_ref(),
                    ty.as_ref(),
                    &mut flat_fields,
                )?;
            }
            FnArg::Receiver(_) => {
                return Err(syn::Error::new_spanned(arg, "generate_parcel_struct does not support self receivers"));
            }
        };
    }
    Ok(flat_fields)
}

fn build_call_args(
    inputs: &syn::punctuated::Punctuated<syn::FnArg, syn::token::Comma>,
    flat_fields: &[FlatField],
) -> syn::Result<Vec<proc_macro2::TokenStream>> {
    use syn::{FnArg, Pat, PatType, Type};

    fn build_arg_expr(
        pat: &Pat,
        ty: &Type,
        flat_fields: &mut std::slice::Iter<'_, FlatField>,
    ) -> syn::Result<proc_macro2::TokenStream> {
        match pat {
            Pat::Ident(pat_ident) => {
                let field = flat_fields
                    .next()
                    .ok_or_else(|| syn::Error::new_spanned(pat_ident, "not enough flattened fields"))?;
                let name = &field.name;
                match ty {
                    Type::Reference(r) =>
                        Ok(if r.mutability.is_some() {
                            quote! { unsafe { mtukai_transferred.#name.as_mut() } }
                        } else {
                            quote! { unsafe { mtukai_transferred.#name.as_ref() } }
                        }),
                    _ => Ok(quote! { mtukai_transferred.#name }),
                }
            }
            Pat::Paren(pat_paren) => build_arg_expr(pat_paren.pat.as_ref(), ty, flat_fields),
            Pat::Reference(pat_ref) => {
                let inner_ty = match ty {
                    Type::Reference(inner_ty) => inner_ty.elem.as_ref(),
                    _ => ty,
                };
                let inner_expr = build_arg_expr(pat_ref.pat.as_ref(), inner_ty, flat_fields)?;
                match ty {
                    Type::Reference(r) if r.mutability.is_some() => Ok(quote! { &mut #inner_expr }),
                    Type::Reference(_) => Ok(quote! { &#inner_expr }),
                    _ => Ok(inner_expr),
                }
            }
            Pat::Tuple(pat_tuple) => {
                let mut elems = Vec::with_capacity(pat_tuple.elems.len());
                let tuple_ty = match ty {
                    Type::Reference(inner_ty) => match inner_ty.elem.as_ref() {
                        Type::Tuple(tuple_ty) => tuple_ty,
                        _ => {
                            return Err(syn::Error::new_spanned(
                                pat,
                                "tuple pattern requires a tuple type",
                            ));
                        }
                    },
                    Type::Tuple(tuple_ty) => tuple_ty,
                    _ => {
                        return Err(syn::Error::new_spanned(
                            pat,
                            "tuple pattern requires a tuple type",
                        ));
                    }
                };
                if pat_tuple.elems.len() != tuple_ty.elems.len() {
                    return Err(syn::Error::new_spanned(
                        pat,
                        "tuple pattern and tuple type have different lengths",
                    ));
                }
                for (elem_pat, elem_ty) in pat_tuple.elems.iter().zip(tuple_ty.elems.iter()) {
                    elems.push(build_arg_expr(elem_pat, elem_ty, flat_fields)?);
                }
                match ty {
                    Type::Reference(r) if r.mutability.is_some() => Ok(quote! { &mut ( #(#elems),* ) }),
                    Type::Reference(_) => Ok(quote! { &( #(#elems),* ) }),
                    _ => Ok(quote! { ( #(#elems),* ) }),
                }
            }
            // Pat::Slice(pat_slice) => {
            //     let mut elems = Vec::with_capacity(pat_slice.elems.len());
            //     for elem in pat_slice.elems.iter() {
            //         elems.push(build_arg_expr(elem, flat_fields)?);
            //     }
            //     Ok(quote! { [ #(#elems),* ] })
            // }
            Pat::Wild(_) | Pat::Rest(_) => Err(syn::Error::new_spanned(
                pat,
                "wildcard and rest patterns are not supported in generated calls",
            )),
            Pat::Or(pat_or) => Err(syn::Error::new_spanned(
                pat_or,
                "or-patterns are not supported because they do not denote a single value",
            )),
            _ => Err(syn::Error::new_spanned(
                pat,
                "currently supported argument patterns are identifiers, tuples, references, and parentheses", // , and slices over tuple/array types",
            )),
        }
    }

    let mut flat_fields = flat_fields.iter();
    let mut arg_exprs = Vec::new();

    for arg in inputs.iter().skip(1) {
        match arg {
            FnArg::Typed(PatType { pat, ty, .. }) => {
                arg_exprs.push(build_arg_expr(pat.as_ref(), ty.as_ref(), &mut flat_fields)?);
            }
            FnArg::Receiver(_) => {
                return Err(syn::Error::new_spanned(arg, "generate_call_args does not support self receivers"));
            }
        }
    }

    if flat_fields.next().is_some() {
        return Err(syn::Error::new_spanned(
            &inputs,
            "flattened fields and function arguments do not match",
        ));
    }

    Ok(arg_exprs)
}

fn generate_parcel_struct(flat_fields : &Vec<FlatField>, implement_impls : bool) -> syn::Result<proc_macro2::TokenStream> {
    use syn::Type;
    fn push_move_stmts(
        field_name: &syn::Ident,
        ty: &Type,
        move_to_main_stmts: &mut proc_macro2::TokenStream,
        move_to_lp_stmts: &mut proc_macro2::TokenStream,
    ) -> syn::Result<()> {
        let field_src = quote! { self.#field_name };
        let field_dst = quote! { (&mut (*dest).#field_name) as * mut _ as *mut u8 };
        match ty {
            Type::Reference(r) => {
                move_to_lp_stmts.extend(quote! { (*dest).#field_name = #field_src.as_ref().wrap_transfer_to_lp()?; });
                if r.mutability.is_some() {
                    move_to_main_stmts.extend(quote! { ((*dest).#field_name).as_mut().wrap_transfer_to_main_sub(#field_src)?;});
                }
            }
            Type::Path(_) => {
                move_to_lp_stmts.extend(quote! {#field_src.wrap_move_to_lp(#field_dst)?;});
                move_to_main_stmts.extend(quote! {#field_src.wrap_move_to_main(#field_dst)?;});
            }
            _ => {
                return Err(syn::Error::new_spanned(ty, "Currently unsupported argument type."));
            }
        }
        Ok(())
    }

    let mut fields = proc_macro2::TokenStream::new();
    let mut move_to_main_stmts = if implement_impls {
        quote! {let dest = dest as * mut Self;}.into()
    } else { proc_macro2::TokenStream::new() };
    let mut move_to_lp_stmts = move_to_main_stmts.clone();
    
    for flat_field in flat_fields {
        let FlatField { name, ty } = flat_field;
        let translated_ty = match ty {
            Type::Reference(syn::TypeReference{elem, ..}) => quote!{NonNull<#elem>},
            Type::Path(_) => quote!{#ty},
            _ => return Err(syn::Error::new_spanned(ty, "Currently unsupported argument type.")),
        };
        fields.extend(quote! { #name: #translated_ty, });
        if implement_impls {
            push_move_stmts( &name, &ty, &mut move_to_main_stmts, &mut move_to_lp_stmts)?;
        }
    }

    Ok(quote! {
        use core::ptr::NonNull;
        struct MtukaiParcel {
            #fields
        }
        impl MovableObject for MtukaiParcel {
            unsafe fn move_to_main(&self, dest: *mut u8) -> Result<(), EspCoproError> { unsafe {
                #move_to_main_stmts
                Ok(())
            }}

            unsafe fn move_to_lp(&self, dest: *mut u8) -> Result<(), EspCoproError> { unsafe {
                #move_to_lp_stmts
                Ok(())
            }}
        }
    }
    .into())
}

/// Marks the entry function of a LP core program.
///
/// Arguments:
/// - `heap_size`: the LP heap size in bytes.
/// - `define_alloc_error`: optional boolean, defaults to `true`.
#[cfg(feature = "is-lp-core")]
#[proc_macro_attribute]
pub fn entry(args: TokenStream, item: TokenStream) -> TokenStream {
    use proc_macro2::Span as Span2;
    use syn::{
        FnArg,
        GenericArgument,
        ItemFn,
        PatType,
        PathArguments,
        Type,
    };

    let entry_args: EntryMacroArgs = match syn::parse(args) {
        Ok(args) => args,
        Err(e) => return e.to_compile_error().into(),
    };
    let heap_size = entry_args.heap_size;
    let heap_size = if heap_size > 0 { quote!(#heap_size) } else {quote!{}};
    let define_alloc_error = entry_args.define_alloc_error;

    // This is a specialized implementation - won't fit other use-cases
    fn to_string(ty: &Type) -> String {
        let mut res = String::new();
        if let Type::Path(p) = ty {
            let segment = p.path.segments.last().unwrap();
            res.push_str(&segment.ident.to_string());

            if let PathArguments::AngleBracketed(g) = &segment.arguments {
                res.push('<');
                let mut pushed = false;
                for arg in &g.args {
                    if pushed {
                        res.push(',');
                    }
                    pushed = true;
                    match arg {
                        GenericArgument::Type(t) => {
                            res.push_str(&to_string(t));
                        },
                        GenericArgument::Const(c) => {
                            res.push_str(&quote! { #c }.to_string());
                        },
                        _ => pushed = false,
                    }
                }
                res.push('>');
            }
        }
        res
    }

    pub(crate) fn make_magic_symbol_name(args: &Vec<&PatType>) -> String {
        let mut res = String::from("__ULP_MAGIC_");
        for &a in args {
            let t = &a.ty;
            let quoted = to_string(t);
            res.push_str(&quoted);
            res.push('$');
        }
        res
    }

    let mtukai_crate = get_crate_name("esp-rs-copro");
    let procmacro_crate = get_crate_name("esp-rs-copro-procmacro");
    let self_crate = get_crate_name("mtukai-projgen");
    let alloc_error_handler =  define_alloc_error.then(|| {
        quote! {
            #[allow(unused)]
            #[alloc_error_handler]
            fn ignore_alloc_error(_: core::alloc::Layout) -> ! {
                loop {}
            }
        }});

    let input = match syn::parse2::<ItemFn>(item.into()) {
        Ok(f) => f,
        Err(e) => return e.to_compile_error().into(),
    };

    if let Some(err) = check_entry_fn_signature(&input) {
        return err.to_compile_error().into();
    }

    let flat_fields = match collect_flat_fields(&input.sig.inputs) {
        Ok(fields) => fields,
        Err(e) => return e.to_compile_error().into(),
    };
    let parcel_struct = match generate_parcel_struct(&flat_fields, false) {
        Ok(ts) => ts,
        Err(e) => return e.to_compile_error().into(),
    };
    let arg_exprs = match build_call_args(&input.sig.inputs, &flat_fields) {
        Ok(exprs) => exprs,
        Err(e) => return e.to_compile_error().into(),
    };

    let mut args = Vec::new();
    for input in input.sig.inputs.iter().skip(1) {
        match input {
            FnArg::Typed(pt) => { args.push(pt); }
            _ => {
                return syn::Error::new(Span2::call_site(), "methods with self are not supported by #[entry]")
                    .to_compile_error().into();
            }
        }
    }

    let orig_name = input.sig.ident.clone();
    let magic_symbol_name = make_magic_symbol_name(&args);
    quote! {
        #procmacro_crate::esp_rs_copro_statics!(#heap_size);
        #alloc_error_handler
        #[allow(non_snake_case)]
        #[unsafe(export_name = "main")]
        pub fn __risc_v_rt__main() {
            use #mtukai_crate::{EspCoproError, movableobject::MovableObject};
            #[unsafe(export_name = #magic_symbol_name)]
            static ULP_MAGIC: [u32; 0] = [0u32; 0];
            unsafe { ULP_MAGIC.as_ptr().read_volatile(); }
            #parcel_struct
            let mtukai_transferred = get_transfer::<MtukaiParcel>().unwrap();
            #orig_name(&mut #self_crate::LpContext::new(), #(#arg_exprs),*);
            core::mem::forget(mtukai_transferred); // Do not free the transferred data, as it is now owned by the main processor.
        }
        #input
    }.into()
}

#[cfg(feature="has-lp-core")]
#[proc_macro_attribute]
pub fn entry(args: TokenStream, item: TokenStream) -> TokenStream {
    use std::path::Path;
    use parse::Error;
    use proc_macro::Span;
    use proc_macro_crate::{FoundCrate, crate_name};
    use syn::{Ident, parse, ItemFn, spanned::Spanned, parse_quote};
    use std::{fs};
    use object::{File, Object, ObjectSection, ObjectSymbol, Section, SectionFlags};

    let args: EntryMacroArgs = match syn::parse(args) {
        Ok(args) => args,
        Err(e) => return e.into_compile_error().into(),
    };

    let hal_crate = get_crate_name(
        if cfg!(feature = "is-lp-core") { "esp-lp-hal" } else { "esp-hal" });
    let mtukai_crate = get_crate_name("esp-rs-copro");
    
    let copro_crate_use = if let Ok(FoundCrate::Name(ref name)) = crate_name("esp-rs-copro") {
        let ident = Ident::new(name, Span::call_site().into());
        quote!{ use #ident ::{ transfer_functions::*, lpbox::LPBox, lpalloc::ImplLPAllocator, movableobject::MovableObject, movableobjectwrapper::*, EspCoproError, try_copro_lock, copro_unlock}; }
    } else { quote!{} };

    let elf_file = args.path;
    if !Path::new(&elf_file).exists() {
        return Error::new(Span::call_site().into(), "File not found")
            .to_compile_error().into();
    }

    let bin_data = fs::read(elf_file).unwrap();
    let obj_file = File::parse(&*bin_data).unwrap();
    let sections = obj_file.sections();
    let mut sections: Vec<Section> = sections
        .into_iter()
        .filter(|section| {
            match section.flags() {
                SectionFlags::Elf{sh_flags: sh} => (sh & u64::from(object::elf::SHF_ALLOC)) != 0,
                _ => false
            }
        }).collect();
    sections.sort_by(|a, b| a.address().partial_cmp(&b.address()).unwrap());

    let mut binary: Vec<u8> = Vec::new();
    let mut last_address = if args.lp_start.is_some() {
        u64::MAX // We do not care.
    } else if cfg!(any(feature = "esp32s3", feature = "esp32s2")) {
        0x0
    } else {
        0x5000_0000
    };

    if sections.is_empty() {
        return Error::new(
            Span::call_site().into(),
            "Given file doesn't seem to have any allocatable sections.",
        ).to_compile_error().into();
    } else if  sections[0].address() < last_address {
        return Error::new(
            Span::call_site().into(),
            format!(
                "First section address is below expected base address (expected >= 0x{:x}, got 0x{:x})",
                last_address,
                sections[0].address()
            ),
        ).to_compile_error().into();
    }

    for section in sections {
        if section.address() > last_address {
            let fill = section.address() - last_address;
            binary.extend(std::iter::repeat(0).take(fill as usize));
        }

        binary.extend_from_slice(section.data().unwrap());
        last_address = section.address() + section.size();
    }

    if let Some(lp_length) = &args.lp_length {
        if binary.len() > (*lp_length as usize) {
            return Error::new(
                lp_length.span(),
                "LP_CODE length exceeds lp_length.",
            ).to_compile_error().into();
        }
    }

    let magic_symbol = if let Some(magic_symbol) = 
        obj_file.symbols().find(|s| s.name().unwrap().starts_with("__ULP_MAGIC_")) {
        magic_symbol.name().unwrap()
    } else {
        return Error::new(
            Span::call_site().into(),
            "Given file doesn't seem to be an LP/ULP core application.",
        ).to_compile_error().into();
    };

    // magic symbol is not cared, currently.

    #[cfg(feature = "esp32c6")]
    let imports = quote! {
        use #hal_crate::lp_core::LpCore;
        use #hal_crate::lp_core::LpCoreWakeupSource;
        use #hal_crate::rtc_cntl::sleep::WakeFromLpCoreWakeupSource;
        #copro_crate_use;
    };
    #[cfg(feature = "esp32s3")]
    let imports = quote! {
        use #hal_crate::ulp_core::UlpCore as LpCore;
        use #hal_crate::ulp_core::UlpCoreWakeupSource as LpCoreWakeupSource;
        use #hal_crate::rtc_cntl::sleep::UlpWakeupSource;
        #copro_crate_use;
    };

    #[cfg(feature = "esp32c6")]
    let rtc_code_start = quote! { _rtc_fast_data_start };
    #[cfg(feature = "esp32s3")]
    let rtc_code_start = quote! { _rtc_slow_data_start };
    
    let input_fn = match syn::parse::<ItemFn>(item.into()) {
        Ok(f) => f,
        Err(e) => return e.to_compile_error().into(),
    };

    if let Some(e) = check_entry_fn_signature(&input_fn) {
        return e.to_compile_error().into();
    }

    fn rewrite_binding(
        arg: &mut syn::FnArg,
        fallback_name: &str,
        err_msg: &str,
    ) -> syn::Result<syn::Ident> {
        if let syn::FnArg::Typed(pt) = arg {
            match pt.pat.as_ref() {
                syn::Pat::Ident(pat_ident) => {
                    if pat_ident.ident != "_" {
                        return Ok(pat_ident.ident.clone());
                        } // if "_", rewriting.
                    },
                syn::Pat::Wild(_) => {}, // OK rewriting.
                _ => { return Err(Error::new(pt.pat.span(), err_msg)); }
            };
            let ident = syn::Ident::new(fallback_name, proc_macro2::Span::call_site());
            pt.pat = Box::new(parse_quote!(#ident));
            Ok(ident)
        } else {
            Err(Error::new(arg.span(), err_msg))
        }
    }

    let mut new_sig = input_fn.sig.clone();
    new_sig.output = parse_quote!(-> Result<(), #mtukai_crate::EspCoproError>);
    let first_arg = match new_sig.inputs.first_mut() {
        Some(arg) => match rewrite_binding(
            arg,
            "mtukai_lpcontext",
            "The first argument of the function marked with #[entry] must be of the form `&mut LpContext`",
        ) {
            Ok(ident) => ident,
            Err(e) => return e.to_compile_error().into(),
        },
        None => {
            return Error::new(
                input_fn.sig.span(),
                "Function must have at least one argument of type `&mut LpContext`",
            ).to_compile_error().into();
        }
    };
    let flat_fields = match collect_flat_fields(&new_sig.inputs) {
        Ok(fields) => fields,
        Err(e) => return e.to_compile_error().into(),
    };
    let parcel_struct = match generate_parcel_struct(&flat_fields, true) {
        Ok(ts) => ts,
        Err(e) => return e.to_compile_error().into(),
    };

    let (transfer, transfer_back) =
        if let Some(a) = obj_file.symbols().find(|s| s.name() == Ok("__COPRO_TRANSFER")).map(|s| s.address()) 
            && new_sig.inputs.len() > 1 {
            let a = a as u32 + if cfg!(feature = "esp32s3") { 0x5000_0000 } else { 0 };
            let mut new_args = proc_macro2::TokenStream::new();
            let mut update_values = proc_macro2::TokenStream::new();
            for ff in flat_fields {
                let name = &ff.name;
                match &ff.ty {
                    syn::Type::Reference(syn::TypeReference{ elem, mutability, .. }) => {
                        if mutability.is_some() {
                            new_args.extend(quote! { #name: NonNull::from_mut(#name), });
                        } else {
                            new_args.extend(quote! { #name: NonNull::from_ref(#name), });
                        }
                    },
                    _ => {
                        new_args.extend(quote! { #name, });
                    }
                }
            }
            (quote!{
                unsafe {
                    use core::alloc::GlobalAlloc;
                    lp_alloc_func = |layout| { 
                        unsafe { get_allocator().as_ref().unwrap().alloc(layout) }
                    }; 
                    lp_dealloc_func = |ptr, layout| {
                        unsafe { get_allocator().as_ref().unwrap().dealloc(ptr, layout); }
                    };
                    lp_get_lp_mem_begin_and_len = || {
                        unsafe {
                            let alc = get_allocator().as_ref().unwrap();
                            (alc.heap.as_ptr() as usize, alc.heap.len())
                        }
                    };
                }
                let mut mtukai_transfer_value = MtukaiParcel {#new_args}; 
                let trans = mtukai_transfer_value.wrap_transfer_to_lp()?;
                unsafe {((#a) as *mut NonNull<MtukaiParcel>).write_volatile(trans);}
            },
            quote!{unsafe {
                mtukai_transfer_value.wrap_transfer_to_main(((#a) as *mut NonNull<MtukaiParcel>).read_volatile())?;
                core::mem::forget(mtukai_transfer_value);
            } })
        } else { (quote! {}, quote! {})};
    let allocsym = obj_file.symbols().find(|s| s.name().map_or(false, |v| v.starts_with("__COPRO_ALLOCATOR_")));
    let allocfun = allocsym.map(|a| {
        let mut addr = a.address() as u32;
        let size = a.name().ok().and_then(|v| v["__COPRO_ALLOCATOR_".len()..].parse::<usize>().ok());
        if cfg!(feature = "esp32s3") {
            addr += 0x5000_0000;
        }
        quote!{
            fn get_allocator() -> *mut ImplLPAllocator<#size> {
                #addr as *mut ImplLPAllocator<#size>
            }
        }
    });
    let alloccall = allocfun.is_some().then(|| quote!{
        unsafe{get_allocator().as_mut().unwrap().init()};
        #transfer
    });

    let copy_dest = if let Some(lp_start) = args.lp_start {
        quote! { (#lp_start as *mut u8) }
    } else {
        quote! { &#rtc_code_start as *const u32 as *mut u8 }
    };

    quote! {
        #new_sig {
            #imports

            #parcel_struct

            static LP_CODE: &[u8] = &[#(#binary),*];
            unsafe extern "C" { static #rtc_code_start: u32; }
            unsafe { core::ptr::copy_nonoverlapping(LP_CODE as *const _ as *const u8, #copy_dest, LP_CODE.len()); }

            #allocfun
            try_copro_lock()?;
            #alloccall
            #first_arg.get_core().run(LpCoreWakeupSource::HpCpu);
            #first_arg.get_rtc().sleep_light(&[&WakeFromLpCoreWakeupSource::new()]);
            #transfer_back
            copro_unlock();
            Ok(())
        }
    }.into()
}
