[package]
name = "list_sum"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "list-sum-main"
path = "./src/bin/main.rs"

[dependencies]
esp-println = { version="0.17.0", features = ["log-04"], optional = true}
esp-backtrace = { version="0.19.0", features = [
    "panic-handler",
    "println",
], optional = true }
esp-bootloader-esp-idf = { version = "0.5.0", optional = true }
esp-hal                = { version = "=1.1.1", features = ["unstable", "log-04"], optional = true }

esp-rs-copro           = { path = "../../mtukai/esp-rs-copro" }
esp-rs-copro-procmacro = { path = "../../mtukai/esp-rs-copro-procmacro" }

esp-lp-hal             = { version = "0.3.0", optional = true }
embedded-hal      = { version = "1.0.0", optional = true }
cfg-if = "1.0.3"
panic-halt = { version = "0.2.0", optional = true }

critical-section = {version ="1.2.0", optional = true }
esp-alloc = { version = "0.10.0", optional = true }

[features]
default = [ "esp32c6" ]
esp32c6 = [ "esp-backtrace?/esp32c6", "esp-bootloader-esp-idf?/esp32c6", "esp-hal?/esp32c6", "esp-lp-hal?/esp32c6", "esp-rs-copro/esp32c6", "esp-alloc?/esp32c6", "esp-rs-copro-procmacro/esp32c6" ]
esp32s3 = [ "esp-backtrace?/esp32s3", "esp-bootloader-esp-idf?/esp32s3", "esp-hal?/esp32s3", "esp-lp-hal?/esp32s3", "esp-rs-copro/esp32s3", "esp-alloc?/esp32s3", "esp-rs-copro-procmacro/esp32s3" ]
has-lp-core = [ "esp-rs-copro/has-lp-core", "esp-rs-copro-procmacro/has-lp-core", "dep:esp-println", "dep:esp-backtrace", "dep:esp-bootloader-esp-idf", "dep:esp-hal", "dep:critical-section", "dep:esp-alloc" ]
is-lp-core = [ "esp-rs-copro/is-lp-core", "esp-rs-copro-procmacro/is-lp-core", "dep:embedded-hal", "dep:esp-lp-hal", "dep:panic-halt" ]

[build-dependencies]
esp-metadata-generated = { version = "0.3.0", features = ["build-script"] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
