[alias]
runx = "run -- --manifest-path ../examples/list_sum/Cargo.toml build"
genx = "run -- --manifest-path ../examples/list_sum/Cargo.toml gen"
showcargo = "run -- --manifest-path ../examples/list_sum/Cargo.toml gen --cargo-toml"
